hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/qm9/hydra/
setup:
  seed: 1
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/peptides
load:
  batch_size: 128 #2048-max 96-default
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/peptides/prgnn.pt
train:
  epochs: 500
  patience: 50
  lr : .001
  wd : 1e-6
model:
  hidden_channels: 300
  dropout: 0.0
  tol : 1e-4
  max_iter : 20
