hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/arxi/hydra/
setup:
  seed: 0
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/arxiv/
load:
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/arxiv/chkpt.pt
train:
  epochs: 2000
  patience: 2000
  lr : .003
  wd : 0
model:
  hidden_channels: 256
  dropout : 0
  phantom_grad : 10
  beta_init : -0.7
  gamma_init : -10.0
  tol : 1e-6
