hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/chains/hydra/
setup:
  seed: 42
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/chains/
data:
  chain_len: 10
  num_chains: 20
  num_classes: 2
  feature_dim: 100
load:
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/chains/test.pt
train:
  epochs: 2000
  patience: 100
  lr : .005
  wd : 1e-6
model:
  hidden_channels: 16
  dropout: 0.1
  phantom_grad : 10
  beta_init : -0.7
  gamma_init : -10.0
  tol : 1e-6