hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/heterophilious/hydra/
setup:
  seed: 42
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/heterophilious/
load:
  split: fixed_05/10/85
  dataset: Roman-empire
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/heterophilious/heterophilious.pt
train:
  epochs: 2000
  patience: 200
  warmup: 100
  lr : 0.01
  wd : 0 #1e-8
model:
  hidden_channels: 256
  dropout: 0.2
  phantom_grad : 1
  beta_init : 1.0
  gamma_init : 0.0
  tol : 1e-4
  max_iter : 20