hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/planetoid/hydra/
setup:
  seed: 20
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/planetoid/
load:
  dataset: cora
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/planetoid/chkpt.pt
  split: public
train:
  epochs: 1500
  patience: 1500
  lr : .01
  wd : 0.0
model:
  hidden_channels: 64
  dropout : .8
  phantom_grad : 10
  beta_init : 0.9
  gamma_init : 0.0
  max_iter : 50
  tol : 1e-4
  fix_params: False