hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/hydra/
setup:
  seed: 2333
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/
load:
  split: fixed_06
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/snap_amz/prgnn.pt
train:
  epochs: 5000
  patience: 100
  lr : 0.009
  wd : 0.00000001
model:
  hidden_channels: 128
  dropout: 0.0
  phantom_grad : 10
  beta_init : 0.5
  gamma_init : -0.2
  tol : 0.0001