hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/wikinet/hydra/
setup:
  seed: 0
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/wikinet/
load:
  dataset: chameleon
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/wikinet/chkpt.pt
  split: geom-gcn
train:
  epochs: 1500
  patience: 100
  lr : .1
  wd : 1e-8
model:
  hidden_channels: 128
  dropout : .5
  phantom_grad : 1
  beta_init : 0.0
  gamma_init : 0.0
  tol : 1e-6